=== lastick1/rexpert/data/schemas/weather.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Схема конфигурационного файла пресетов погоды",
  "definitions": {
    "weatherPreset": {
      "type": "object",
      "required": ["CloudConfig", "CloudLevel", "CloudHeight", "Turbulence", "PrecLevel", "PrecType"],
      "additionalProperties": false,
      "properties": {
        "CloudConfig": {
          "type": "string"
        },
        "CloudLevel": {
          "type": "string"
        },
        "CloudHeight": {
          "type": "string"
        },
        "Turbulence": {
          "type": "string"
        },
        "PrecLevel": {
          "type": "string"
        },
        "PrecType": {
          "type": "string"
        }
      }
    }
  },
  "required": ["$schema", "maps", "moscow", "stalingrad", "kuban"],
  "additionalProperties": false,
  "properties": {
    "$schema": {},
    "maps": {
      "type": "array",
      "title": "Доступные в конфиге карты",
      "items": {
        "enum": ["moscow", "stalingrad", "kuban"]
      }
    },
    "weibull_parameter": {
      "type": "number",
      "title": "Параметр распределения Вейбулла для генерации погоды.",
      "description": "Чем ближе к 1, тем чаще будут выпадать неблагоприятные пресеты (приближение к равномерному распределнию). При 10 90% будет на 4й и 5й пресеты погоды.",
      "minimum": 1,
      "default": 2.4,
      "maximum": 10
    },
    "moscow": {
      "type": "object",
      "title": "Пресеты погоды для ТВД Москвы",
      "required": ["au", "wi"],
      "additionalProperties": false,
      "properties": {
        "au": {
          "type": "object",
          "title": "Летний сезон",
          "patternProperties": {
            "^\\d+$": {
              "$ref": "#/definitions/weatherPreset"
            }
          }
        },
        "wi": {
          "type": "object",
          "title": "Осенний сезон",
          "patternProperties": {
            "^\\d+$": {
              "$ref": "#/definitions/weatherPreset"
            }
          }
        }
      }
    },
    "stalingrad": {
      "type": "object",
      "title": "Пресеты погоды для ТВД Сталинграда",
      "required": ["wi", "su", "au"],
      "additionalProperties": false,
      "properties": {
        "wi": {
          "type": "object",
          "title": "Зимний сезон",
          "patternProperties": {
            "^\\d+$": {
              "$ref": "#/definitions/weatherPreset"
            }
          }
        },
        "su": {
          "type": "object",
          "title": "Летний сезон",
          "patternProperties": {
            "^\\d+$": {
              "$ref": "#/definitions/weatherPreset"
            }
          }
        },
        "au": {
          "type": "object",
          "title": "Осенний сезон",
          "patternProperties": {
            "^\\d+$": {
              "$ref": "#/definitions/weatherPreset"
            }
          }
        }
      }
    },
    "kuban": {
      "type": "object",
      "title": "Пресеты погоды для ТВД Кубани",
      "required": ["su", "au"],
      "additionalProperties": false,
      "properties": {
        "su": {
          "type": "object",
          "title": "Летний сезон",
          "patternProperties": {
            "^\\d+$": {
              "$ref": "#/definitions/weatherPreset"
            }
          }
        },
        "au": {
          "type": "object",
          "title": "Осенний сезон",
          "patternProperties": {
            "^\\d+$": {
              "$ref": "#/definitions/weatherPreset"
            }
          }
        }
      }
    }
  }
}

=== lastick1/rexpert/configs/weather.json
{
  "$schema": "../data/schemas/weather.json",
  "maps": ["moscow", "stalingrad"],
  "moscow": {
    "au": {
      "0": {
        "CloudConfig": "summer\\00_Clear_00\\sky.ini",
        "CloudLevel": "[500,501]",
        "CloudHeight": "200",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "1": {
        "CloudConfig": "summer\\00_Clear_01\\sky.ini",
        "CloudLevel": "[500,501]",
        "CloudHeight": "200",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "2": {
        "CloudConfig": "summer\\00_Clear_02\\sky.ini",
        "CloudLevel": "[500,501]",
        "CloudHeight": "200",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "3": {
        "CloudConfig": "summer\\00_Clear_03\\sky.ini",
        "CloudLevel": "[500,501]",
        "CloudHeight": "200",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "4": {
        "CloudConfig": "summer\\00_Clear_04\\sky.ini",
        "CloudLevel": "[500,501]",
        "CloudHeight": "200",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "5": {
        "CloudConfig": "summer\\00_Clear_05\\sky.ini",
        "CloudLevel": "[500,501]",
        "CloudHeight": "200",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "6": {
        "CloudConfig": "summer\\00_Clear_06\\sky.ini",
        "CloudLevel": "[500,501]",
        "CloudHeight": "200",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "7": {
        "CloudConfig": "summer\\00_Clear_07\\sky.ini",
        "CloudLevel": "[500,501]",
        "CloudHeight": "200",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "8": {
        "CloudConfig": "summer\\00_Clear_08\\sky.ini",
        "CloudLevel": "[500,501]",
        "CloudHeight": "200",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "9": {
        "CloudConfig": "summer\\00_Clear_09\\sky.ini",
        "CloudLevel": "[500,501]",
        "CloudHeight": "200",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "10": {
        "CloudConfig": "summer\\01_Light_00\\sky.ini",
        "CloudLevel": "[500,2000]",
        "CloudHeight": "[400,800]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "11": {
        "CloudConfig": "summer\\01_Light_01\\sky.ini",
        "CloudLevel": "[500,2000]",
        "CloudHeight": "[300,500]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "12": {
        "CloudConfig": "summer\\01_Light_02\\sky.ini",
        "CloudLevel": "[500,2000]",
        "CloudHeight": "[300,700]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "13": {
        "CloudConfig": "summer\\01_Light_03\\sky.ini",
        "CloudLevel": "[500,2000]",
        "CloudHeight": "[300,500]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "14": {
        "CloudConfig": "summer\\01_Light_04\\sky.ini",
        "CloudLevel": "[500,2000]",
        "CloudHeight": "[300,600]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "15": {
        "CloudConfig": "summer\\01_Light_05\\sky.ini",
        "CloudLevel": "[500,2000]",
        "CloudHeight": "[400,800]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "16": {
        "CloudConfig": "summer\\01_Light_06\\sky.ini",
        "CloudLevel": "[500,2000]",
        "CloudHeight": "[300,600]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "17": {
        "CloudConfig": "summer\\01_Light_07\\sky.ini",
        "CloudLevel": "[500,2000]",
        "CloudHeight": "[300,700]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "18": {
        "CloudConfig": "summer\\01_Light_08\\sky.ini",
        "CloudLevel": "[500,2000]",
        "CloudHeight": "[400,800]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "19": {
        "CloudConfig": "summer\\01_Light_09\\sky.ini",
        "CloudLevel": "[500,2000]",
        "CloudHeight": "[400,800]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "20": {
        "CloudConfig": "summer\\02_Medium_00\\sky.ini",
        "CloudLevel": "[600,2000]",
        "CloudHeight": "[500,1000]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "21": {
        "CloudConfig": "summer\\02_Medium_01\\sky.ini",
        "CloudLevel": "[600,2000]",
        "CloudHeight": "[500,1000]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "22": {
        "CloudConfig": "summer\\02_Medium_02\\sky.ini",
        "CloudLevel": "[600,2000]",
        "CloudHeight": "[500,1000]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "23": {
        "CloudConfig": "summer\\02_Medium_03\\sky.ini",
        "CloudLevel": "[600,2000]",
        "CloudHeight": "[300,700]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "24": {
        "CloudConfig": "summer\\02_Medium_04\\sky.ini",
        "CloudLevel": "[600,2000]",
        "CloudHeight": "[500,1000]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "25": {
        "CloudConfig": "summer\\02_Medium_05\\sky.ini",
        "CloudLevel": "[600,2000]",
        "CloudHeight": "[500,1000]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "26": {
        "CloudConfig": "summer\\02_Medium_06\\sky.ini",
        "CloudLevel": "[600,2000]",
        "CloudHeight": "[400,850]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "27": {
        "CloudConfig": "summer\\02_Medium_07\\sky.ini",
        "CloudLevel": "[600,2000]",
        "CloudHeight": "[500,1000]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "28": {
        "CloudConfig": "summer\\02_Medium_08\\sky.ini",
        "CloudLevel": "[600,2000]",
        "CloudHeight": "[400,900]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "29": {
        "CloudConfig": "summer\\02_Medium_09\\sky.ini",
        "CloudLevel": "[600,2000]",
        "CloudHeight": "[600,1200]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "30": {
        "CloudConfig": "summer\\03_Heavy_00\\sky.ini",
        "CloudLevel": "[600,1200]",
        "CloudHeight": "[600,1200]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "31": {
        "CloudConfig": "summer\\03_Heavy_01\\sky.ini",
        "CloudLevel": "[600,1200]",
        "CloudHeight": "[600,1200]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "32": {
        "CloudConfig": "summer\\03_Heavy_02\\sky.ini",
        "CloudLevel": "[600,1200]",
        "CloudHeight": "[600,1200]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "33": {
        "CloudConfig": "summer\\03_Heavy_03\\sky.ini",
        "CloudLevel": "[600,1200]",
        "CloudHeight": "[600,1200]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "34": {
        "CloudConfig": "summer\\03_Heavy_04\\sky.ini",
        "CloudLevel": "[600,1200]",
        "CloudHeight": "[600,1200]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "35": {
        "CloudConfig": "summer\\03_Heavy_05\\sky.ini",
        "CloudLevel": "[600,1200]",
        "CloudHeight": "[600,1200]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "36": {
        "CloudConfig": "summer\\03_Heavy_06\\sky.ini",
        "CloudLevel": "[600,1200]",
        "CloudHeight": "[700,1400]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "37": {
        "CloudConfig": "summer\\03_Heavy_07\\sky.ini",
        "CloudLevel": "[600,1200]",
        "CloudHeight": "[600,1200]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "38": {
        "CloudConfig": "summer\\03_Heavy_08\\sky.ini",
        "CloudLevel": "[600,1200]",
        "CloudHeight": "[600,1200]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "39": {
        "CloudConfig": "summer\\03_Heavy_09\\sky.ini",
        "CloudLevel": "[600,1200]",
        "CloudHeight": "[700,1500]",
        "PrecLevel": "10",
        "PrecType": "0",
        "Turbulence": "0"
      },
      "40": {
        "CloudConfig": "summer\\04_Overcast_00\\sky.ini",
        "CloudLevel": "[600,1200]",
        "CloudHeight": "200",
        "PrecLevel": "10",
        "PrecType": "1",
        "Turbulence": "0"
      },
      "41": {
        "CloudConfig": "summer\\04_Overcast_01\\sky.ini",
        "CloudLevel": "[600,1200]",
        "CloudHeight": "300",
        "PrecLevel": "10",
        "PrecType": "1",
        "Turbulence": "0"
      },
      "42": {
        "CloudConfig": "summer\\04_Overcast_02\\sky.ini",
        "CloudLevel": "[600,1200]",
        "CloudHeight": "300",
        "PrecLevel": "10",
        "PrecType": "1",
        "Turbulence": "0"
      },
      "43": {
        "CloudConfig": "summer\\04_Overcast_03\\sky.ini",
        "CloudLevel": "[600,1200]",
        "CloudHeight": "400",
